FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html

#Grant permissions to the random OpenShift user for Nginx system folders
RUN chmod -R a+rwx /var/cache/nginx /var/run /var/log/nginx /etc/nginx

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
